runtime: nodejs10
service: random-youtube
env_variables:
  NODE_ENV: 'production'
  SESSION_SECRET: 'bubbles'
  CLIENT_ID: '903887188265-dhb0v0lcvqhjc42fg0smc7j7jjiaah3v.apps.googleusercontent.com'
  CLIENT_SECRET: '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'
  REDIRECT_URL: ''
